Sequence and shot folder grouping
ynput/ayon-shotgrid pull request #129
Opened 2024-09-10 12:03 UTC by kalisp

## Changelog Description
Synchronized `sequences` and `shots` were stored directly in root of the AYON project previously. This PR adds configurable option to set main `assets`, `sequences` and `shots` subdirectories.

![image](https://github.com/user-attachments/assets/7f951eea-a6c5-454f-9ec2-a631b6fe6bba)

## Additional info
There might be discussion needed for current implementation of `shots` without sequences in SG (if it makes actually sense in production). I implemented it according to requirements, but it might be just misunderstanding. 

! For running projects `ayon+settings://shotgrid/compatibility_settings/folder_locations` should be purged to keep original implementation. (Or maybe changed defaults OR changed initialization of this addon???)

## Testing notes:

1. check `ayon+settings://shotgrid/compatibility_settings/folder_locations` if it matches your requirements
2. synchronize from Shotgrid to AYON
3. `shots` folder is for shots without sequences (which is possible in SG)

2024-09-11 18:56 UTC, fabiaserra commented
I personally don't think this feature makes much sense. I imagine this comes after this request https://github.com/ynput/ayon-shotgrid/issues/126 ? As I commented there, I think it makes sense to group all asset entities under a folder called `assets` and all shot based entities under one called `shots` (or whatever) but splitting each entity into its own category beats the purpose in my opinion. Are shots parented to sequences going under the root `sequences` folder?

2024-09-12 13:58 UTC, kalisp commented on server/settings/main.py
> +        disabled=True,
Fffff...unwanted, reverted. Thanks for noticing.

2024-09-13 10:02 UTC, kalisp commented
`Are shots parented to sequences going under the root sequences folder` they would now (but they shouldn't according to requirements, `sequences` should contain only sequences)

I am open to ideas how to configure it to be more universal as this is sponsored  issue, but I agree it might not apply to all use cases, same as yours doesn't.

2024-09-13 11:52 UTC, fabiaserra commented
> `Are shots parented to sequences going under the root sequences folder` they would now (but they shouldn't according to requirements, `sequences` should contain only sequences)

So where are shots parented to sequences go? Or a sequence child of an episode and that episode having sequences and then shots? Could you put some examples of the different cases?

2024-09-13 12:10 UTC, BigRoy commented
I'm so clueless about these conversations - doesn't shotgrid just have hierarchies itself? And shouldn't we just adhere to that hierarchy 1:1? Or what makes this so complex?

2024-09-13 12:16 UTC, fabiaserra commented
> I'm so clueless about these conversations - doesn't shotgrid just have hierarchies itself? And shouldn't we just adhere to that hierarchy 1:1? Or what makes this so complex?

Yeah I'm a bit confused too tbh, I thought the request was to have it just on disk (which wouldn't require to create the entities in the server and it's just a template thing) and just as a means to encapsulate ALL of the shots (with its respective hierarchy) within. On the other hand, if they want those categories to show up on the UIs that's something we can do in the frontend agnostic of shotgrid as the folder types exist, it's basically just an extension to the existing icons?

2024-10-07 12:03 UTC, tweak-wtf commented
@antirotor asked me to chime in to explain my usecase as i'm also interested in this feature and we've talked about it last week.
lemme share my thoughts on this...

SG doesn't have the ability to structure entities into generic folders as AYON.
Using SG's project tracking features allows you to create hierarchies like `Episode->Sequence->Shot` however it's currently not possible to place these SG hierarchies in a custom AYON folder.
Syncing AYON entities to SG is easy since we just need `folder_name` and `folder_type` of AYON and create the SG entities respectively as SG takes care of the linking.

so I believe this issue boils down to being able to use custom AYON folders as roots for SG hierarchies.

assume an SG project tracking setting for assets as `AssetType->Asset` and the following AYON hierarchy for assets:
```
├── build
│   └── assets
│       └── Prop
│       ├── Character
│       └── Environment
``` 

I want to have my SG-created assets to show up in `/build/assets/{asset[type]}/` in AYON.

### Suggestion
We get SG's project tracking settings for enabled entity types and expose them as part of a new settings field in the compatibility settings. Each SG tracking setting gets a string field representing the AYON folder hierarchy to follow.
E.g.:

SG Asset: AssetType->Asset    -->     AYON hierarchy to follow: /build/assets/{asset[type]}/

If a user doesn't want to use custom AYON hierarchies and basically start with a blank AYON project populated from SG they'd leave all lineedits empty and SG's project tracking settings will be followed (even if flat? error otherwise?).

I think this way we could support any AYON hierarchy with any SG project tracking.

2024-10-07 13:45 UTC, fabiaserra commented
> Using SG's project tracking features allows you to create hierarchies like Episode->Sequence->Shot however it's currently not possible to place these SG hierarchies in a custom AYON folder.

that's not entirely true? I can change the project anatomy template and place all of those entities under any custom folder that I want? What it's true is that those wouldn't be on different individual custom folders but that's why I raised my doubts, on which case would you want that? Why would you want the shots children of a specific sequence under a different custom folder? And if that's not what you want and you basically just want like what we have in our fork, do you just want two separate custom folders for the `assets` type entities (build) and the `shots` (episode, sequence, shot...)? If the latter, the solution is much simpler than what's being suggested here.

> Syncing AYON entities to SG is easy since we just need folder_name and folder_type of AYON and create the SG entities respectively as SG takes care of the linking.

Sorry but that's not entirely true either, unless you set the parent/child relationships in SG those entities will be childless

> I want to have my SG-created assets to show up in /build/assets/{asset[type]}/ in AYON.

This kind of points me to believe what you want is what I was referring to simply separating the `assets` entities and the `shots`-based entities and so if that's the case, I don't think we should be doing any changes to `ayon-shotgrid` and it should all be `ayon-core`, basically allowing for more granular control on the template syntax to express the different types of folders. In our fork, as I commented here https://github.com/ynput/ayon-shotgrid/issues/126#issuecomment-2329235843, I added support for a new key on the template called `{assets_or_shots}` that basically contains the string `shots` or `assets` depending on what type of entity it is. Expanding on that... it would be pretty simple to make that token contain `/build/assets` or `/shots` instead and those changes would only require a few extra lines of code and avoid adding extra complexity to this codebase AND it would work for all the other project management addons (ftrack, kitsu...) and not be specific to this

2024-10-07 21:10 UTC, tweak-wtf commented
my specific use case is to create SG Assets under `/build/assets` in AYON following the SG tracking settings to result in `/build/assets/{asset[type]}/{asset[name]}`.
i don't want to break the integrity of SG tracking settings. rather use them under a new root.
no SG shots linked to an SG Sequence broken apart into different folders in AYON or so.

it's more about how to treat asset types that are parentless in terms of entity tracking settings, like Sequence (by default?) in SG.
To do that i'm suggesting to merge an implicit SG tracking settings path and an explicit AYON path together, optionally.
e.g. tracking setting `Sequence->Shot` for an SG Shot `sh010` in sequence `seq01` with AYON folder `/sequences` would build `/sequences/seq01/sh010`. and if a user creates an SG Shot with no SG Sequence? yikes, but we could place it in the next available root in `/sequences/<NONE>/sh010` which would be `/sequences`.

in #126 we unfortunately don't have the SG tracking settings to check which would help and tbh i don't quite get that use case either. might be all flat tracking settings in SG, might be breaking `Sequence->Shot` tracking. 
for all everything flat i could imagine having a bunch of parentless shots being assembled by different sequences/edits but i'm assuming.

2024-10-07 21:21 UTC, fabiaserra commented
> my specific use case is to create SG Assets under `/build/assets` in AYON following the SG tracking settings to result in `/build/assets/{asset[type]}/{asset[name]}`. i don't want to break the integrity of SG tracking settings. rather use them under a new root. no SG shots linked to an SG Sequence broken apart into different folders in AYON or so.
> 
> it's more about how to treat asset types that are parentless in terms of entity tracking settings, like Sequence (by default?) in SG. To do that i'm suggesting to merge an implicit SG tracking settings path and an explicit AYON path together, optionally. e.g. tracking setting `Sequence->Shot` for an SG Shot `sh010` in sequence `seq01` with AYON folder `/sequences` would build `/sequences/seq01/sh010`. and if a user creates an SG Shot with no SG Sequence? yikes, but we could place it in the next available root in `/sequences/<NONE>/sh010` which would be `/sequences`.
> 
> in #126 we unfortunately don't have the SG tracking settings to check which would help and tbh i don't quite get that use case either. might be all flat tracking settings in SG, might be breaking `Sequence->Shot` tracking. for everything flat i could imagine having a bunch of parentless shots being assembled by different sequences/edits but i'm assuming.

I'm honestly still pretty confused as to what you are asking. Have you played much with the current `ayon-shotgrid`, the anatomy templates and tried to sync different entities from SG? If entities don't have a parent they are already going to a flat hierarchy as I would expect and the current implementation of `ayon-shotgrid` DOES use the project tracking settings as a means to know what's the hierarchy of the entities that you want to map in AYON.

For example, we have these parentless shots on all SG projects: `_edit_shot`, `_2d_shot` and `_3d_shot` and when we sync them into AYON they go under this location:
```
> ll /proj/dev_000/shots/
total 0
0 drwxrwsrwx 10 root ax_users  8 Jan 18  2024 ./
0 drwxrwsrwx 17 root ax_users 15 Sep 27 03:05 ../
0 drwxrwsrwx  6 root ax_users  4 Jan 24  2024 000_seq/
0 drwxrwsrwx  4 root ax_users  2 Jan 24  2024 _2d_shot/
0 drwxrwsrwx  4 root ax_users  2 Mar 13  2024 _3d_shot/
0 drwxrwsrwx  3 root ax_users  1 Jan  3  2024 _edit_shot/
```
And our `assets` are going under here:
```
> ll /proj/dev_000/assets/
total 0
0 drwxrwsrwx  6 root ax_users  4 Jul 26  2023 ./
0 drwxrwsrwx 17 root ax_users 15 Sep 27 03:05 ../
0 drwxrwsrwx  5 root ax_users  3 May 10 13:00 Prop/
0 drwxrwsrwx  2 root ax_users  0 May 10  2023 Characters/
0 drwxrwsrwx  2 root ax_users  0 May 10  2023 Locations/
```

It seems like the only change you want on top of what I already have is to have the `assets` under an extra nested folder called `build`, the rest would be the same? and as I suggested, adding that extra folder should be much simpler than what you are suggesting doing here unless I'm not understanding correctly

2024-10-08 08:43 UTC, tweak-wtf commented
true, i haven't used the anatomy presets since i thought it's only used when creating an AYON project from an existing SG one. i always start off projects in AYON with a predefined folder hierarchy and have the docker stack create the SG project.
when syncing SG entities to AYON I know they are following their tracking settings. but they do not respect existing AYON folder hierarchy. that's why i have to tell prods/coords that they need to create entities in AYON and not in SG. however, i would like to give them the freedom to create entities in AYON or SG, their choice.

i'm having some issues explaining my use case more than by saying: i want to be able to sync SG entities to a configurable root folder in AYON in order to support any custom AYON hierarchy respecting SG's tracking settings for that entity. 

however, if i get u right using the anatomy templates is able to create SG entities in AYON under a custom root folder.
so with the latest versions of `ayon-core` and `ayon-shotgrid`, which template settings of an anatomy preset do i need to change to achieve SG assets being synced to `/assets` (or `/build/assets`) then following the tracking settings `AssetType->Asset` just as u do?

always down for having a quick call btw.

2024-10-08 14:03 UTC, fabiaserra commented
> true, i haven't used the anatomy presets since i thought it's only used when creating an AYON project from an existing SG one. 

Not really, anatomy presets are agnostic from SG, they are just a means to set how the entities live on disk

> i always start off projects in AYON with a predefined folder hierarchy and have the docker stack create the SG project. when syncing SG entities to AYON I know they are following their tracking settings. but they do not respect existing AYON folder hierarchy. that's why i have to tell prods/coords that they need to create entities in AYON and not in SG. however, i would like to give them the freedom to create entities in AYON or SG, their choice.

Is this because you are creating an actual AYON folder entity named "build" for you to have that extra grouping for `/build/assets/...` as opposed to just having that `build` and `assets` folders ONLY on disk? In our server, the same hierarchy that we have in AYON is mapped exactly the same in SG and viceversa so we are able to create the entities anywhere and they will look the same and the creation of the `shots` and `assets` folders are ONLY operating system folders, not the "AYON Folder", we simply set these folders on the anatomy preset so this extra folder gets created on the project structure on disk

> i'm having some issues explaining my use case more than by saying: i want to be able to sync SG entities to a configurable root folder in AYON in order to support any custom AYON hierarchy respecting SG's tracking settings for that entity.

If I'm understanding your problem correctly, I think the issue is that you are trying to create these kind of typeless folders on AYON ("build", "assets", "shots"...) and that makes sense why it's an issue on the syncing between both as those extra folder hierarchy don't make much sense in Shotgrid. What's your use case for having those extra folders in AYON though and not simply on disk?

> however, if i get u right using the anatomy templates is able to create SG entities in AYON under a custom root folder. so with the latest versions of `ayon-core` and `ayon-shotgrid`, which template settings of an anatomy preset do i need to change to achieve SG assets being synced to `/assets` (or `/build/assets`) then following the tracking settings `AssetType->Asset` just as u do?

You are not able to do that with the current state of `ayon-core` and `ayon-shotgrid` but in our fork of `ayon-core`, we did this simple change on the template_data: https://github.com/fabiaserra/ayon-core/blob/release/alkemyx/client/ayon_core/pipeline/template_data.py#L107 that allows us to use this token on the anatomy `{assets_or_shots}` that basically contains the string `assets` or `shots` and when the entities get created/referenced on disk that path contains one or the other. Extending on that functionality, one could expose something similar on the settings so users could configure what the value of this token contains depending on the folder type, so you would be able to define that for "asset" folder types... this string contains `/build/assets` instead of just `assets`, and similarly, for `episodes`, `sequences` and `shots` they could contain `shots` or any other folder structure. But as I said, I think that should only be a matter of extending the functionality of the anatomy templates so you have more control on how the folders get created ON disk.

However, if I understood correctly, your problem is that these custom folders are not only on disk, they are actual extra "AYON Folders" that you want to have in your project. If that's the case, I think that could be something supported on the AYON server itself where you are able to create extra grouping folders and on the `ayon-shotgrid` you would be able to choose which ones to ignore so the hierarchy just bypasses them

2024-10-09 21:33 UTC, tweak-wtf commented
> If I'm understanding your problem correctly, I think the issue is that you are trying to create these kind of typeless folders on AYON ("build", "assets", "shots"...) and that makes sense why it's an issue on the syncing between both as those extra folder hierarchy don't make much sense in Shotgrid. What's your use case for having those extra folders in AYON though and not simply on disk?

yes exactly!
i don't really see them as typeless since afaik they do have a type, it's just `Folder` 
so basically every time i said folder i was referring to an "AYON Folder" of type `Folder`. oh jeez the lingo :D sorry if that didn't come across.
tbh, i just kinda like the resemblance to the os filesystem of AYON's browser. i can imagine doing more cool stuff with it than an os filesystem folder. i like to have AYON folders created based on some template to init an AYON project's hierarchy prefilled with some test shots, assets, tasks and such and have those synced back to SG.
that's what i meant with: SG doesn't have the ability to structure entities into generic folders as AYON.
i believe kitsu doesn't, aquarium should (it's node-based) and i don't know about the others.

> However, if I understood correctly, your problem is that these custom folders are not only on disk, they are actual extra "AYON Folders" that you want to have in your project. If that's the case, I think that could be something supported on the AYON server itself where you are able to create extra grouping folders and on the ayon-shotgrid you would be able to choose which ones to ignore so the hierarchy just bypasses them

yeah, extra actual typeless AYON folders "groups(?)" could be a thing!
OT: would also love to see product grouping on the AYON server's browser synced to a dcc desktop loader.

2024-10-10 13:30 UTC, kalisp commented
> However, if I understood correctly, your problem is that these custom folders are not only on disk, they are actual extra "AYON Folders" that you want to have in your project.

Yes, it started as client request where they didnt like that shots and sequences weren't grouped. 
State without this PR. 
<img width="222" alt="chrome_Al2KHP1JC1" src="https://github.com/user-attachments/assets/313bc3c2-1027-4d49-a97a-db39fbe18ee0">
![image](https://github.com/user-attachments/assets/92179b1b-69b0-4dd8-9b31-0695b69f27b1)

2024-10-10 13:43 UTC, fabiaserra commented
> yes exactly! i don't really see them as typeless since afaik they do have a type, it's just `Folder` so basically every time i said folder i was referring to an "AYON Folder" of type `Folder`. oh jeez the lingo :D sorry if that didn't come across.

Yeah... it's quite confusing and I wonder if the term Ynput chose actually is what drove you to end up doing this workflow hahaha I personally don't see the disk folder structure the same way as the entity hierarchy on AYON or SG and I would hope the icons are already kind of acting the same purpose as giving a "category" to the different entities without needing an extra folder, but I guess I could see someone preferring the extra categorization by adding extra folders.

> SG doesn't have the ability to structure entities into generic folders as AYON. i believe kitsu doesn't, aquarium should (it's node-based) and i don't know about the others.

I don't think that's an AYON only thing though, you could probably do the same in SG by creating custom entities that can be parented to other existing entities so they act like "AYON Folders", although as I said, I think that would complicate things quite a bit as all of a sudden a lot of the assumptions we can do in most pipelines working on features/episodic/animation are no longer that true and it certainly makes this `ayon-shotgrid` addon much more complex and error-prone (similar to having to do the same for `ayon-ftrack` and any other sync addons)

> yeah, extra actual typeless AYON folders "groups(?)" could be a thing! 

I think that's how the solution to this issue should be implemented TBH, supporting "dummy category" folders in AYON natively so they can be easily ignored on the different sync addons that don't support the same structure by design

> OT: would also love to see product grouping on the AYON server's browser synced to a dcc desktop loader.

Probably misunderstanding what you mean but product groups do show up on the loaders of AYON?

2024-10-10 13:46 UTC, fabiaserra commented
> Yes, it started as client request where they didnt like that shots and sequences weren't grouped. State without this PR. <img alt="chrome_Al2KHP1JC1" width="222" src="https://private-user-images.githubusercontent.com/4457962/375397727-313bc3c2-1027-4d49-a97a-db39fbe18ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjczODIsIm5iZiI6MTcyODU2NzA4MiwicGF0aCI6Ii80NDU3OTYyLzM3NTM5NzcyNy0zMTNiYzNjMi0xMDI3LTRkNDktYTk3YS1kYjM5ZmJlMThlZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMTMzMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc1NGMyZGQ4YWU5ZDNlNjU2ZmQ3NDkyNDVjN2M0YTEzMGI5NWU0MjZiYjQ3NDgwOWY4OTQyZjVkMjA4NzUyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1hHIu4xDYuMUs6zaKFMOwTVaaxnZbfWsRAeTxtkJ_Z0"> ![image](https://private-user-images.githubusercontent.com/4457962/375397831-92179b1b-69b0-4dd8-9b31-0695b69f27b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjczODIsIm5iZiI6MTcyODU2NzA4MiwicGF0aCI6Ii80NDU3OTYyLzM3NTM5NzgzMS05MjE3OWIxYi02OWIwLTRkZDgtOWIzMS0wNjk1YjY5ZjI3YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMTMzMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU2ZmJlZTVmNjJkOGVjMDc0MTRlYjM1YjI3ZmQ0OWFhYjcxYzUxMmVmODI4NDE3NDBmOGNjY2M3M2YzYmExOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.URF8IB2N55gZ5YtHLfJRzaQtxKZlhtydF6IkxPNSBa0)

I think this image is particularly misleading as that Shot doesn't have any episode or sequence as parent. If it did, the `sh010` wouldn't be sitting there at the roof of the project. You can always name your entities however you want and if for example the episodes were named `ep101` and the sequence `seq_tst`, that shot would be on a hierarchy of `ep101/seq_tst`, which is already pretty easy in my opinion to see the difference of hierarchy between the `assets` and the `shots`

2024-10-10 14:22 UTC, kalisp commented
Yet client would expect something like `episodes/ep101/seq_tst`.

2024-10-10 14:38 UTC, fabiaserra commented
> Yet client would expect something like `episodes/ep101/seq_tst`.

Is that already working with the work of this PR? Could you provide some production examples of the category folders created in a project? Can they have any number of nested category folders or just one?

2024-10-14 17:28 UTC, dee-ynput commented
> Could you provide some production examples of the category folders created in a project? Can they have any number of nested category folders or just one?

Hello @fabiaserra 
This PR is implementing our client request. If you're interested in production examples I invite you to deploy and test it, or wait for the release 👍
Thanks for your participation in this thread, it's always usefull to challenge implementation.
The request iteself is not up for debate though.

If some supporting users ask for the `{asset_or_shot}` token, we'll be more than happy to add it and it would make you way of dealing with hierarchy available too.
That is not our goal here though.

Cheers!

2024-10-14 18:54 UTC, fabiaserra commented
> Hello @fabiaserra This PR is implementing our client request. If you're interested in production examples I invite you to deploy and test it, or wait for the release 👍 

I'm interested because merging your releases can break other people's forks of `ayon-shotgrid`, like ours, and discussing about other options it's good for you and the rest of the community. Asking for a more clear explanation of what the PR tries to do is just the bare minimum of a controversial PR. If you are 100% confident about the implementation go ahead, we will do our own assessment when we try merge the next release (if we do)

> The request iteself is not up for debate though.

I wasn't debating the request, just the implementation of it and helping to find out a better solution

> Thanks for your participation in this thread, it's always usefull to challenge implementation.

You are welcome but honestly things like this just disencourage me in continuing to participate

2024-11-14 12:28 UTC, jakubjezek001 commented on services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
> +            parent_is_project = isinstance(ay_parent_entity, ProjectEntity)
```suggestion
            parent_is_project = ay_parent_entity.entity_type == "project"
```

2024-11-14 12:28 UTC, jakubjezek001 commented on services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
> +            parent_is_project = isinstance(ay_parent_entity, ProjectEntity)
`ProjectEntity` object does not exists.

2024-11-14 12:31 UTC, jakubjezek001 commented
@kalisp it seems some uncommited changes are still on your machine and need to be pushed. 

My tests were showing some ProjectEntity rises (metnioned in code). And also here is output of the project sync. 
![image](https://github.com/user-attachments/assets/4f149962-f8bd-4b44-bb4a-56c5e9f74533)

This is working only partly. Shots should also be in its own folder `Shots` so it is alligned with your image.

2024-11-14 12:32 UTC, jakubjezek001 requested changes
Perhaps some some local changes needs to be pushed so this could be reviewed again.

2024-11-14 16:30 UTC, kalisp commented on services/shotgrid_common/ayon_shotgrid_hub/match_shotgrid_hierarchy_in_ayon.py
> +            parent_is_project = isinstance(ay_parent_entity, ProjectEntity)
Fixed.

2024-11-14 16:38 UTC, tweak-wtf commented
the suggested server setting look great. exactly what i had in mind. This also gives enough flexibility to account for entities other than `Shot` or `Asset`, e.g. `Lens`.

> It is important to mention that we need to have Shotgrid Entity type filtering for each preset, so we could add ultiple entity type related presets. Yes it does have a caviate and it is possible multiple usage of single entity type with different reparenting types. This would ofcourse could kill the synchronization so we would need to find a way to validate those presets.

good catch! also we'd have to check against SG tracking settings.
with these new AYON server settings a user might end up configuring different AYON parent folders for `Sequence` and `Shot` while using a SG tracking setting like `Sequence->Shot`. Then the service wouldn't know what to do as it would try to create the sequence in a different location than the shot effectively breaking the link. not hehe.
seems this validation could turn out to be somewhat tricky. maybe we could (for now) restrict the presets to be configured to `Shots` and `Assets` only?  maybe this could also be handled by simply writing good docs that warn a user about potentially faulty configurations, maybe giving examples and why they don't make sense.

at this point i just wanna note again that this is all about following an SG entities tracking setting in AYON under a specific parent folder, not about breaking those hierarchy links.

> I believe that this settings model should be able provide the universal functionality we would need for such feature. What do you thing @tweak-wtf, would this be fiesable for your production?

yes i completely agree with everything u wrote. love the server settings approach which is more than feasible, although validating erroneous user preset configuration might become a challenge.

2024-11-15 14:17 UTC, jakubjezek001 commented
@tweak-wtf please look into #147 for some update on the settings.

2024-11-28 09:56 UTC, MilaKudr approved these changes
Both methods work fine for me. For some reason there is a one minute delay (waiting) between pressing the Sync button (SG -> AYON) since the Processor service begin to do something, lets see if this can be improved.

2024-11-29 12:34 UTC, jakubjezek001 requested changes
```
2024-11-29 12:03:58.215 INFO: Event has been processed... setting to finished!
2024-11-29 12:03:58.971 ERROR: Unable to create Task <9f491990ae4111efb21b85431f85a5f6> in Shotgrid!
Traceback (most recent call last):
  File "C:\CODE\__YNPUT\ayon-shotgrid\services\shotgrid_common\ayon_shotgrid_hub\update_from_ayon.py", line 83, in create_sg_entity_from_ayon_event
    sg_entity = _create_sg_entity(
                ^^^^^^^^^^^^^^^^^^
  File "C:\CODE\__YNPUT\ayon-shotgrid\services\shotgrid_common\ayon_shotgrid_hub\update_from_ayon.py", line 340, in _create_sg_entity
    raise ValueError(
ValueError: Parent does not exist in Shotgrid!None <None>
```

This is happening only with Transmitter once a AY project is set to `shotgrid_push` activated for auto syncing based on AY changes. 

*****
Edit: 
So the another examination of the issue discovered following issue at this testing:
- Shots in Relocate Root workflow is synchronized but parent (in AY under a Sequence) is not correctly set. 
- The above issue was caused by wrong setting Folder type on shot (Shotgrid is not supporting Folder type)

2024-11-29 13:02 UTC, jakubjezek001 commented
We will be sorting the parenting issue in consequent PR @kalisp please. But let's not do new release until the parenting is solved @m-u-r-p-h-y @tatiana-ynput .

2024-11-29 13:02 UTC, jakubjezek001 approved these changes

2024-11-29 13:33 UTC, merged