Fix versions not in teh correct folder
ynput/ayon-shotgrid pull request #39
Opened 2023-10-20 15:49 UTC by Minkiu

*  `client` Bump Shotgrid API version to v3.4.0
*  `ayon_shotgrid_hub` Better logging when creating from SG event
* `services.utils` Version's parent field is always entity

2023-10-25 11:56 UTC, Minkiu commented
I'm gonna test that the three services build and work, and perform a publish before merging and making a new release.

2023-10-25 15:24 UTC, Minkiu commented
Found more issues, specially when creating Tasks types, which now its almost fixed, but the backend/frontedn seems to be doing something weird, so it breaks the `transmitter`

2023-10-25 16:21 UTC, antirotor requested changes
I've hit this:

```
shotgun_api3.shotgun.Fault: API read() invalid/missing string entity 'type':
{"type"=>"LocalStore",
 "return_fields"=>["mac_path", "windows_path", "linux_path"],
 "filters"=>{"logical_operator"=>"and", "conditions"=>[]},
 "return_only"=>"active",
 "paging"=>{"entities_per_page"=>1, "current_page"=>1},
 "api_return_image_urls"=>true,
 "return_paging_info_without_counts"=>false}
 ```
in `integrate_shotgrid_publish.py` - I guess that it's because I don't have `localStore` set on the SG project. We should handle this case somehow.

2023-10-25 16:21 UTC, antirotor commented on client/ayon_shotgrid/plugins/publish/integrate_shotgrid_publish.py
> +            sg_local_store = sg.find_one(
This throws `NameError`, it should be

```suggestion
            sg_local_store = sg_session.find_one(
```

2023-10-25 17:29 UTC, Minkiu commented
Okay, I fixed the bug spotted by @antirotor and a plethora of errors that surfaced, since the PR is becoming unwieldy, I'll merge and make a release tomorrow first thing, so we can rebase other PRs and @m-u-r-p-h-y can test stuff on his end too.

2023-10-26 09:44 UTC, Minkiu commented
> I've hit this:
> 
> ```
> shotgun_api3.shotgun.Fault: API read() invalid/missing string entity 'type':
> {"type"=>"LocalStore",
>  "return_fields"=>["mac_path", "windows_path", "linux_path"],
>  "filters"=>{"logical_operator"=>"and", "conditions"=>[]},
>  "return_only"=>"active",
>  "paging"=>{"entities_per_page"=>1, "current_page"=>1},
>  "api_return_image_urls"=>true,
>  "return_paging_info_without_counts"=>false}
> ```
> 
> in `integrate_shotgrid_publish.py` - I guess that it's because I don't have `localStore` set on the SG project. We should handle this case somehow.

That's something that needs to be set up at a Shotgrid instance level, so I would assume by the time someone tries to publish they already have it enabled? Are you publishing against `https://ynput.shotgrid.autodesk.com` ?

2023-10-26 10:09 UTC, Minkiu commented
Just tested the publish and it worked:
![image](https://github.com/ynput/ayon-shotgrid/assets/1800151/215a4a87-7d64-4c5f-a9dc-e002608e6099)

2023-10-26 10:09 UTC, merged